GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnJhZCIsImlhdCI6MTY4OTAwMTQzMn0.3zodaDJXEJN01JA8b2qbsYCs6Ge95uuiqUmE3rNb2Ak

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "Brad"
}